### ISSUE TITLE
EventEmitter.removeListener('change', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`.

### ISSUE THREAD

**Issue by roqkabel** [shubhambathe1/react-native-responsive-screen-hooks#49]
Please is there a way I can help resolve this issue.

EventEmitter.removeListener('change', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`.

I am developing a mobile app that demands screen rotation 

Has anyone come across this.

Thank you. 

Environment:
 Expo SDk Version : ~45.0.0
Package version :  ^1.4.2

**Comment by shubhambathe1** [comment]
@roqkabel Please go ahead, do the required changes and raise a PR. I will merge after reviewing it. By the way is this breaking any existing functionality. If so please describe the issue you're facing. Thanks.
